sudo: false
language: nix

addons:
  apt:
    packages:
    - gnutls-bin
    - sharutils
    - nodejs
    - gfortran
    - python-minimal
    - python-pip
    - python3.5-minimal

cache:
  directories:
  - $HOME/local
  - $HOME/.cask
  - $HOME/node_modules
  - $HOME/.cache/pip
  - $HOME/.evm
  - $HOME/.emacs.d
  - $HOME/Library/Caches/Homebrew
  - $HOME/.pyenv
  - $HOME/Library/Caches/pip

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/cask/bin:$HOME/local/R/bin:$HOME/local/julia-1.1.0/bin:$PATH

matrix:
  include:
    - os: linux
      env: EMACS_CI=emacs-25-1 IPYTHON=5.8.0
    - os: linux
      env: EMACS_CI=emacs-26-2 IPYTHON=6.5.0
    - os: linux
      env: EMACS_CI=emacs-26-3 IPYTHON=7.5.0
    - os: osx
      language: generic
      env: EMACS_CI=emacs-25-2 IPYTHON=5.8.0 TOXENV=py27

  allow_failures:
    - env: EMACS_CI=emacs-snapshot

install:
  - cp -pr $HOME/.cask .
  - sh tools/install-virtualenv.sh
  - |
    if [ "x$TRAVIS_OS_NAME" = "xosx" ]; then
      eval "$(pyenv init -)" ;
      pyenv activate $TOXENV ;
    fi
  - pip install --user jupyter ipython\<=$IPYTHON jedi\<=0.13.3
  - pip install --user numpy
  - pip install --user matplotlib
  - |
    if [[ "x$TRAVIS_PYTHON_VERSION" == x3* ]]; then
      pip install --user jupyterhub ;
      sudo npm install -g configurable-http-proxy ;
      pip install --user jupyterhub-dummyauthenticator ;
    fi
  - sh tools/install-R.sh
  - sh tools/install-julia.sh
  - jupyter kernelspec list
  - curl --version
  - ipython --version

before_script:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - emacs --version
  - sh tools/install-cask.sh

script:
  - make test-install
  - |
    if [[ "x$TRAVIS_PYTHON_VERSION" == x3* ]]; then
      make test-jupyterhub
    fi
  - rm -rf $HOME/.matplotlib $HOME/.cache/fontconfig
  - make test || ( ( zip -q - log/{testein,testfunc,ecukes}.* 2>/dev/null | uuencode log.zip ) && ( printf "To diagnose, travis logs -i | dos2unix | sed '/^begin 644/,/^end/!d' | uudecode" ) && false)
