sudo: false
language: emacs-lisp

addons:
  apt:
    packages:
    - gnutls-bin
    - sharutils

os:
  - linux
  - osx

cache:
  directories:
  - $HOME/local

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$PATH
  matrix:
    - EVM_EMACS=emacs-25.2-travis IPYTHON=6.2.1
    - EVM_EMACS=emacs-26.1-travis IPYTHON=7.0.1

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-snapshot

install:
  - pip install jupyter ipython\<=$IPYTHON
  - jupyter kernelspec list
  - ipython --version

before_script:
  - sh tools/install-evm.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - sh tools/install-cask.sh

script:
  - make test || ( ( zip -q - log/{testein,testfunc,ecukes}.* 2>/dev/null | uuencode log.zip ) && ( printf "To diagnose, travis logs -i | dos2unix | sed '/^begin 644/,/^end/!d' | uudecode" ) && false )
