sudo: false
language: python

addons:
  apt:
    packages:
    - gnutls-bin
    - sharutils

cache:
  directories:
  - $HOME/local

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$PATH

matrix:
  include:
    - os: linux
      python: 2.7
      env: EVM_EMACS=emacs-25.2-travis IPYTHON=5.8.0
    - os: linux
      python: 3.5
      env: EVM_EMACS=emacs-26.1-travis IPYTHON=6.2.1
    - os: linux
      python: 3.6
      env: EVM_EMACS=emacs-26.1-travis IPYTHON=7.0.1
    - os: osx
      language: generic
      env: EVM_EMACS=emacs-25.2 IPYTHON=5.8.0 TOXENV=py27

  allow_failures:
    - env: EVM_EMACS=emacs-snapshot

install:
  - sh tools/install-virtualenv.sh
  - if [ "x$TRAVIS_OS_NAME" = "xosx" ]; then eval "$(pyenv init -)" ; pyenv activate $TOXENV ; fi
  - pip install jupyter ipython\<=$IPYTHON
  - jupyter kernelspec list
  - ipython --version

before_script:
  - sh tools/install-evm.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - sh tools/install-cask.sh

script:
  - make test || ( ( zip -q - log/{testein,testfunc,ecukes}.* 2>/dev/null | uuencode log.zip ) && ( printf "To diagnose, travis logs -i | dos2unix | sed '/^begin 644/,/^end/!d' | uudecode" ) && false )
