sudo: false
language: python

addons:
  apt:
    packages:
    - gnutls-bin
    - sharutils

cache:
  directories:
  - $HOME/local

python:
  - "2.7"
  - "3.6"

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$PATH
  matrix:
    - EVM_EMACS=emacs-25.2-travis EL_REQUEST_BACKEND=curl
    - EVM_EMACS=emacs-26.1-travis EL_REQUEST_BACKEND=curl

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-snapshot

install:
  - pip install jupyter ipython\<=6.4.0
  - jupyter kernelspec list

before_script:
  - sh tools/install-evm.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - sh tools/install-cask.sh

script:
  - make test || ( ( zip -q - log/{testein,testfunc,ecukes}.* 2>/dev/null | uuencode log.zip ) && false )
