sudo: false
language: python

addons:
  apt:
    packages:
    - gnutls-bin
    - python-tornado
    - python-zmq
    - python-jinja2
    - python-jsonschema

cache:
  directories:
  - $HOME/local

python:
  - "2.7"

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$PATH
  matrix:
    - EVM_EMACS=emacs-25.2-travis EL_REQUEST_BACKEND=curl
    - EVM_EMACS=emacs-26.1-travis EL_REQUEST_BACKEND=curl

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-snapshot

install:
  - pip install jupyter ipython\<=6.4.0
  - add-apt-repository ppa:jonathonf/python-2.7 -y
  - apt-get update
  - apt-get install python2.7
  - python2.7 -m pip install ipykernel
  - python2.7 -m ipykernel install --user

before_script:
  - sh tools/install-evm.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - sh tools/install-cask.sh
  - cask install

script:
  - make test
